[".config/zsh/plugins/powerlevel10k"]
    type = "git-repo"
    url = "https://github.com/romkatv/powerlevel10k.git"
    refreshPeriod = "168h"
[".config/zsh/plugins/zsh-autosuggestions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions.git"
    refreshPeriod = "168h"
[".config/zsh/plugins/zsh-notify"]
    type = "git-repo"
    url = "https://github.com/marzocchi/zsh-notify.git"
    refreshPeriod = "168h"
[".config/zsh/plugins/zsh-nvm"]
    type = "git-repo"
    url = "https://github.com/lukechilds/zsh-nvm.git"
    refreshPeriod = "168h"
[".config/zsh/plugins/zsh-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    refreshPeriod = "168h"
